
server:
  port: 8003
spring:
  application:
    name: eureka-server  #指定服务名称
eureka:
  instance:
    hostname: replica2  #指定主机地址
  client:
    fetch-registry: true  #指定是都要从注册中心获取服务
    register-with-eureka: true #指定是否要注册到注册中心
    service-url:
      defaultZone: http://replica1:8002/eureka/